languageCode = "en"
languageName = "English"
weight = 1
title = "Cloud Native Prague"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo.png"
  description = "Cloud Native Prague meetup community website"
  copyright = "Shaped by pubel.dev"

 [author]
   name = "Cloud Native Prague"
   image = "img/logo.png"
   imageQuality = 96
   headline = "Best Cloud Native Community in Prague!"
   bio = "cloudnativeprague.cz is Cloud Native Community in Prague. We are organizing meetups and other events"
   links = [
     { link = "https://community.cncf.io/cloud-native-prague/" },
     { github = "https://github.com/cloud-native-prague/meetups" },
     { slack = "https://slack.cloudnativeprague.cz/" },
     { linkedin = "https://cz.linkedin.com/company/cloud-native-prague" },
     { youtube = "https://records.cloudnativeprague.cz/" },
   ]